"""Add individually authored, distinct practice problems; preserve all existing IDs."""
import json
from pathlib import Path
banks={'math':[],'rw':[],'science':[]}
def add(bank,domain,skill,q,choices,exp,diff='medium',kind=None,passage=None):
    index=len(banks[bank]); correct=choices[0]; shift=index%4
    choices=choices[shift:]+choices[:shift]
    item=dict(id=f'variety-{bank}-{index+1}',family=f'variety-{bank}-{index+1}',domain=domain,skill=skill,q=q,choices=choices,ans=choices.index(correct),exp=exp,diff=diff,source='Original practice modeled on published test skills')
    if kind:item['kind']=kind
    if passage:item['passage']=passage
    assert len(set(choices))==4
    banks[bank].append(item)
def m(domain,skill,q,choices,exp,diff='medium'):add('math',domain,skill,q,list(map(str,choices)),exp,diff)
def r(domain,skill,passage,q,choices,exp,diff='medium'):add('rw',domain,skill,q,choices,exp,diff,'reading',passage)
def w(domain,skill,q,choices,exp,diff='medium'):add('rw',domain,skill,q,choices,exp,diff,'writing')
m('Algebra','Linear equations in one variable','If 3(x − 4) = 2x + 7, what is x?',[19,11,5,-19],'Distribute to get 3x − 12 = 2x + 7. Subtract 2x and add 12: x = 19.','easy')
m('Algebra','Linear functions','A reservoir contains 240 liters. A pump removes water at 8 liters per minute. Which expression gives the liters remaining after t minutes, before the reservoir empties?',['240 − 8t','240 + 8t','8 − 240t','240t − 8'],'The starting amount is 240. Each minute removes 8, so subtract 8t.','easy')
m('Algebra','Linear equations in two variables','A line passes through (2, 9) and (6, 21). What is its y-intercept?',[3,6,9,12],'Slope = (21 − 9)/(6 − 2) = 3. Substitute (2,9) into y = 3x + b: b = 3.')
m('Algebra','Systems of two linear equations','A theater sold 30 tickets. Adult tickets cost $12 and student tickets cost $7. Revenue was $285. How many adult tickets were sold?',[15,10,20,25],'Let a be adults. Students = 30 − a. Then 12a + 7(30 − a) = 285, so 5a = 75 and a = 15.')
m('Algebra','Linear inequalities','A delivery costs $6 plus $1.50 per kilogram. A customer can spend at most $24. What is the greatest permitted mass in kilograms?',[12,16,20,28],'Write 6 + 1.5m ≤ 24. Subtract 6 and divide by 1.5 to get m ≤ 12.','easy')
m('Algebra','Systems of two linear equations','For what value of k does the system 2x + 3y = 8 and 4x + 6y = k have infinitely many solutions?',[16,8,12,24],'The second left side is twice the first. Its right side must also be twice 8, or 16, for the equations to describe the same line.','hard')
m('Algebra','Linear functions','The table gives x = 0, 2, 5 and f(x) = 7, 13, 22. If f is linear, what is f(9)?',[34,27,29,40],'The output increases 6 when x increases 2, so slope = 3. f(x) = 3x + 7; f(9) = 34.')
m('Advanced Math','Equivalent expressions','For x ≠ 3, which expression is equivalent to (x² − 9)/(x − 3)?',['x + 3','x − 3','x² + 3','1'],'Factor x² − 9 into (x − 3)(x + 3), then cancel x − 3. The restriction prevents division by zero.','easy')
m('Advanced Math','Quadratic equations','The equation x² + bx + 12 = 0 has solutions −3 and −4. What is b?',[7,-7,1,12],'The factors are (x + 3)(x + 4) = x² + 7x + 12. Thus b = 7.')
m('Advanced Math','Nonlinear functions','A ball’s height is h(t) = −5t² + 20t + 1. At what time t does it reach its greatest height?',[2,1,4,5],'A downward-opening parabola reaches its maximum at t = −b/(2a) = −20/(−10) = 2. This asks for time, not height.')
m('Advanced Math','Exponential functions','A machine worth $8,000 loses 15% of its value each year. Which model gives its value after t years?',['8000(0.85)^t','8000(1.15)^t','8000 − 0.15t','8000(15)^t'],'Losing 15% leaves 85% each year. Repeated multiplication by 0.85 gives 8000(0.85)^t.')
m('Advanced Math','Radical equations','What is the solution to √(2x + 9) = x, where x ≥ 0?',[ '1 + √10','1 − √10','√10','10'],'Squaring gives x² − 2x − 9 = 0, so x = 1 ± √10. Only 1 + √10 is nonnegative and satisfies the original equation.','hard')
m('Advanced Math','Nonlinear functions','If f(x) = x² − 4 and g(x) = 3x + 1, what is f(g(2))?',[45,7,9,21],'First compute g(2) = 7. Then f(7) = 49 − 4 = 45. The order matters.')
m('Advanced Math','Quadratic equations','For what value of c does x² − 10x + c = 0 have exactly one distinct real solution?',[25,10,20,100],'One real solution occurs when the discriminant is zero: 100 − 4c = 0. Hence c = 25.','hard')
m('Advanced Math','Equivalent expressions','If x + 1/x = 5 and x ≠ 0, what is x² + 1/x²?',[23,25,27,10],'Square both sides: x² + 2 + 1/x² = 25. Subtract 2 to obtain 23.','hard')
m('Advanced Math','Exponential functions','The function p(t) = 120(2)^(t/3) models a population. How many time units does it take for the population to double?',[3,2,6,120],'Doubling occurs when the exponent increases by 1. Since the exponent is t/3, t must increase by 3.','easy')
m('Problem-Solving & Data Analysis','Percentages','A price is reduced by 20%, then the reduced price is increased by 20%. What percent of the original price is the final price?',[96,100,104,80],'The multipliers are 0.80 and 1.20. Their product is 0.96, so the final price is 96% of the original.')
m('Problem-Solving & Data Analysis','Measures of center','Five test scores have a mean of 78. Four scores are 72, 75, 80, and 83. What is the fifth score?',[80,78,82,85],'The required total is 5 × 78 = 390. The four known scores total 310. The missing score is 80.','easy')
m('Problem-Solving & Data Analysis','Probability','Of 40 survey respondents, 18 bike to school. Of those 18, 6 also take the bus sometimes. A respondent who bikes is selected. What is the probability that this respondent also sometimes takes the bus?',['1/3','3/20','9/20','2/3'],'The condition restricts the group to 18 bikers. Six of them also take the bus, so the probability is 6/18 = 1/3.')
m('Problem-Solving & Data Analysis','Unit rates','A car uses 3 gallons to travel 84 miles. At the same rate, how many gallons are needed to travel 196 miles?',[7,6,8,9],'The car travels 84/3 = 28 miles per gallon. Divide 196 by 28 to get 7 gallons.','easy')
m('Problem-Solving & Data Analysis','Ratios and proportional relationships','A map uses a scale of 1 centimeter to 8 kilometers. Two towns are 3.5 centimeters apart on the map. How far apart are they in kilometers?',[28,24,11.5,2.29],'Multiply map distance by the scale: 3.5 × 8 = 28 kilometers.','easy')
m('Problem-Solving & Data Analysis','Statistical inference','A random sample of 200 voters includes 118 who support a proposal. Which estimate of supporters among 5,000 voters is based on this sample?',[2950,1180,2500,3900],'The sample proportion is 118/200 = 0.59. Apply it to the population: 0.59 × 5000 = 2950. This is an estimate, not an exact count.')
m('Problem-Solving & Data Analysis','Measures of spread','Data set A is 2, 4, 6, 8, 10. Data set B is 22, 24, 26, 28, 30. How do their standard deviations compare?',['They are equal.','B’s is 20 greater.','B’s is 10 times A’s.','A’s is zero.'],'Adding the same constant shifts the mean and each data value equally. Distances from the mean stay unchanged, so standard deviation is unchanged.')
m('Problem-Solving & Data Analysis','Scatterplots','A model predicts y = 2.5x + 8. At x = 4, the observed value of y is 21. What is the residual, defined as observed minus predicted?',[3,-3,18,29],'The predicted value is 2.5(4) + 8 = 18. Residual = 21 − 18 = 3.')
m('Geometry & Trigonometry','Circles','A circle has equation (x − 4)² + (y + 2)² = 49. What is its radius?',[7,49,4,2],'In standard form the right side is r². Thus r = √49 = 7. The center is (4, −2).','easy')
m('Geometry & Trigonometry','Area and volume','A cone has radius 3 and height 8. What is its volume?',['24π','72π','18π','12π'],'Use V = (1/3)πr²h = (1/3)π(9)(8) = 24π.')
m('Geometry & Trigonometry','Similar triangles','Two similar triangles have corresponding side lengths 6 and 15. The smaller triangle has area 12. What is the larger triangle’s area?',[75,30,48,150],'The length scale is 15/6 = 2.5. Areas scale by 2.5² = 6.25, so the larger area is 12 × 6.25 = 75.')
m('Geometry & Trigonometry','Right triangle trigonometry','In a right triangle, sin θ = 5/13 for an acute angle θ. What is cos θ?',['12/13','5/12','13/12','8/13'],'The opposite side and hypotenuse are proportional to 5 and 13. The adjacent side is √(169 − 25) = 12, giving cos θ = 12/13.')
m('Geometry & Trigonometry','Circles','An arc subtends a central angle of 72° in a circle with circumference 30. What is the arc length?',[6,12,15,24],'The angle is 72/360 = 1/5 of a full circle. The arc length is 30/5 = 6.','easy')
m('Geometry & Trigonometry','Area and volume','A rectangular prism’s length and width are doubled while its height is halved. Its original volume is 40. What is its new volume?',[80,40,160,20],'Volume scales by 2 × 2 × 1/2 = 2. Thus the new volume is 2 × 40 = 80.')
m('Algebra','Linear equations in one variable','A number is increased by 8, and the result is divided by 3. The quotient is 6. What is the original number?',[10,26,2,18],'Write (x + 8)/3 = 6. Multiply by 3 and subtract 8 to obtain x = 10.','easy')
m('Algebra','Linear functions','A line perpendicular to y = −2x + 5 has what slope?',['1/2','−1/2','2','−2'],'Perpendicular slopes multiply to −1. The negative reciprocal of −2 is 1/2.')
m('Advanced Math','Nonlinear equations','If 2^(x+1) = 32, what is x?',[4,5,3,16],'Write 32 as 2^5. Equal bases give x + 1 = 5, so x = 4.','easy')
m('Advanced Math','Nonlinear functions','A quadratic function has zeros −2 and 5 and passes through (0, −20). Which expression defines it?',['2(x + 2)(x − 5)','(x + 2)(x − 5)','2(x − 2)(x + 5)','−2(x + 2)(x − 5)'],'The zeros give f(x) = a(x + 2)(x − 5). At x = 0 this is −10a = −20, so a = 2.','hard')
m('Problem-Solving & Data Analysis','Percentages','A quantity rises from 80 to 100. By what percentage does it increase?',[25,20,80,125],'The increase is 20. Divide by the original 80: 20/80 = 0.25 = 25%.','easy')
m('Geometry & Trigonometry','Angles','Two parallel lines are crossed by a transversal. One interior angle is 114°. What is the measure of the interior angle on the same side of the transversal?',[66,114,57,76],'Same-side interior angles sum to 180°. Subtract 114° to get 66°.','easy')
r('Craft & Structure','Words in Context','The pianist’s first interpretation was restrained: she avoided dramatic changes in volume, allowing the melody’s small shifts to carry the performance.','As used in the text, “restrained” most nearly means', ['controlled','prevented','uncertain','interrupted'],'The following description explains the word: she limits dramatic changes. “Controlled” describes this measured style; she is not prevented from playing.','easy')
r('Craft & Structure','Words in Context','The revised model accommodates the new observations without abandoning the principles that made the original model useful.','As used in the text, “accommodates” most nearly means',['incorporates','houses','praises','predicts'],'The model includes the observations in its explanation. “Incorporates” fits; physical housing and praise do not describe a model’s function.')
r('Craft & Structure','Words in Context','The historian challenges the prevailing account of the treaty, arguing that letters written before negotiations reveal a different motive.','As used in the text, “prevailing” most nearly means',['widely accepted','recently discovered','legally binding','carefully hidden'],'An account the historian challenges as dominant is widely accepted. The passage does not say it was newly discovered or legally binding.')
r('Information & Ideas','Central Ideas and Details','A poet drafted her collection in two languages. Rather than translating a completed version, she moved between languages as she wrote, letting an image in one language suggest a new rhythm in the other.','Which choice best states the main idea?',['Writing in two languages shaped the poet’s creative process.','The poet translated every finished poem exactly.','One language prevented the poet from using imagery.','The collection compares the histories of two languages.'],'Both the images and rhythms develop through movement between languages. The passage describes composition, not exact translation or language history.','easy')
r('Information & Ideas','Inferences','In a seed experiment, all groups received the same amount of water. Seeds in darkness germinated as often as seeds exposed to light, but their shoots were longer and paler.','Which inference is best supported?',['Light conditions affected shoot development without changing the observed germination rate.','Darkness prevented seeds from sprouting.','Water amount caused the differences between groups.','Longer shoots necessarily indicate healthier plants.'],'Germination frequency was similar, while shoot length and color differed. Water was held constant; health was not measured.')
r('Information & Ideas','Command of Evidence','A researcher argues that commuters respond more to reliable arrival times than to shorter average travel times.','Which hypothetical finding would most directly support this claim?',['Commuters chose a predictable 25-minute route over a route averaging 20 minutes with frequent delays.','The fastest route had the fewest traffic lights.','All surveyed commuters traveled on weekdays.','A new bus route reduced both average travel time and delays.'],'Only the first finding separates predictability from average speed and shows commuters choosing predictability. The last changes both factors, so it cannot isolate the preference.','hard')
r('Information & Ideas','Quantitative Evidence','A survey recorded the percentage of visitors who returned within a month: garden, 42%; observatory, 18%; aquarium, 35%; history museum, 27%. A writer claims that the aquarium had a higher return rate than the museum but a lower rate than the garden.','Which values support the writer’s claim?',['35% is greater than 27% and less than 42%.','18% is less than 27% and 35%.','42% is greater than 18% and 27%.','27% is greater than 18% and less than 42%.'],'The claim is about the aquarium relative to two specific sites. Its 35% lies between the museum’s 27% and garden’s 42%.','easy')
r('Craft & Structure','Text Structure and Purpose','For years the species was identified by the shape of its leaves. A genetic study now indicates that plants with nearly identical leaves can belong to different species. The authors recommend combining leaf measurements with genetic evidence.','Which choice best describes the structure?',['It describes an established method, presents a limitation, and proposes a revised approach.','It introduces a hypothesis and reports evidence that fully confirms it.','It compares two equally successful methods and rejects both.','It lists unrelated discoveries in chronological order.'],'The text moves from leaf identification to genetic evidence showing a limitation, then recommends combining methods.')
r('Craft & Structure','Cross-Text Connections', 'Text 1: A critic argues that recorded concerts can preserve details of a performance that listeners in the hall might miss.\n\nText 2: Another critic notes that recordings cannot reproduce the sense of musicians and listeners responding to one another in a shared space.','On which point would the critics most likely agree?',['A recording offers a different experience from attending a live performance.','Recordings always capture less musical detail than live concerts.','Live audiences do not influence musical performances.','Recordings have no value to listeners.'],'Both identify differences between recordings and live attendance, though they emphasize different advantages. Neither denies all value to recordings.')
r('Information & Ideas','Inferences','A ceramicist keeps small cracks visible when repairing a bowl, filling them with a contrasting material. She calls the finished object a record of use rather than a return to its first appearance.','Which inference is best supported?',['The ceramicist treats the bowl’s history as part of its value.','The ceramicist tries to make damage impossible to notice.','The bowl cannot hold its original shape after repair.','The contrasting material is the only substance that can repair bowls.'],'Calling the repair a record of use supports valuing its history. Visible contrasting cracks contradict hiding damage; physical limitations are not stated.','easy')
r('Craft & Structure','Words in Context','The editor found the essay’s conclusion qualified: it supported the proposal only if the city could first secure funding.','As used in the text, “qualified” most nearly means',['limited by a condition','written by an expert','fully proven','formally approved'],'The word is explained by “only if.” The support depends on funding, making it conditional.')
r('Information & Ideas','Command of Evidence','An urban planner claims that some residents avoid a park because its entrance is difficult to find, rather than because they dislike its amenities.','Which finding would best support the planner’s claim?',['Visits rose after clear entrance signs were added, although park amenities remained unchanged.','The park has fewer benches than a nearby park.','Residents prefer parks with more trees.','The park opened ten years before a nearby park.'],'Changing signs while holding amenities unchanged connects accessibility information to visits. Other findings do not isolate the claimed reason.')
r('Craft & Structure','Text Structure and Purpose','The novelist describes a busy market in vivid detail before revealing that the main character has noticed none of it: he is listening for a familiar voice among the crowd.','What is the most likely function of the market description?',['To contrast the surroundings’ variety with the character’s narrow focus.','To demonstrate the character’s expertise in commerce.','To explain why the market will close soon.','To show that the character has no particular purpose.'],'The reveal contrasts a richly described scene with attention fixed on one voice. It supplies no expertise or closing information.')
r('Information & Ideas','Inferences','A linguist found that speakers used a newly coined verb with unfamiliar nouns in predictable ways, even though those exact combinations had never appeared in the examples they studied.','Which conclusion is best supported?',['Speakers applied a pattern beyond the specific examples they encountered.','Speakers memorized every combination they later produced.','The new verb had no grammatical pattern.','All speakers used identical vocabulary.'],'Producing unseen but predictable combinations supports generalizing a pattern, rather than memorizing combinations.','hard')
r('Craft & Structure','Cross-Text Connections','Text 1: A researcher measures the success of a city’s tree program by the number of trees planted.\n\nText 2: A second researcher argues that trees that die soon after planting provide little lasting benefit, so programs should monitor survival as well.','How would the second researcher most likely respond to the first researcher’s measure?',['It should be supplemented with information about how many planted trees survive.','It is useful only if no trees are ever planted.','It already measures long-term tree survival directly.','It proves that every planting program fails.'],'The second researcher questions the completeness of the planting count and proposes survival monitoring, not abandoning planting.')
r('Information & Ideas','Quantitative Evidence','Seedling height (cm) after four weeks:\nSoil A: untreated 12, supplemented 18.\nSoil B: untreated 15, supplemented 17.\nA student concludes that the supplement increased height more in Soil A than in Soil B.','Which comparison supports the conclusion?',['The increase was 6 cm in Soil A and 2 cm in Soil B.','Untreated seedlings were 3 cm taller in Soil B than in Soil A.','Supplemented seedlings were 18 cm tall in Soil A.','The heights totaled 30 cm in Soil A and 32 cm in Soil B.'],'Compute each treatment difference: 18 − 12 = 6 and 17 − 15 = 2. The claim concerns increases, not totals or untreated values.')
r('Information & Ideas','Central Ideas and Details','A composer designed a piece in which performers choose the order of several short sections. Each section is carefully written, but no single sequence is required. Performances therefore share material while differing in overall shape.','Which choice best states the main idea?',['The piece combines fixed musical material with flexibility in how it is arranged.','Performers compose every note while playing.','Every performance follows the same sequence.','The composer avoids writing any short sections.'],'The sections are fixed, while their order is chosen by performers. Both parts are essential to the main idea.','easy')
r('Craft & Structure','Words in Context','The biologist calls the proposed explanation provisional because observations from only one breeding season are available.','As used in the text, “provisional” most nearly means',['tentative','irrelevant','permanent','precise'],'Limited observations mean the explanation is subject to revision. “Tentative” expresses that lack of finality.','easy')
w('Standard English Conventions','Boundaries','The telescope detected a faint signal ___ further analysis showed that it came from a nearby satellite.\nWhich choice completes the text so that it conforms to Standard English?',['; however,',', however,','however',': however'],'Each side is an independent clause. A semicolon joins them; a comma follows the introductory adverb however. A comma alone cannot join the clauses.')
w('Standard English Conventions','Subject-Verb Agreement','Neither the sketches nor the final portrait ___ available for viewing.\nWhich choice completes the text so that it conforms to Standard English?',['is','are','have been','were'],'With neither/nor, the verb agrees with the nearer subject. “Portrait” is singular, so use “is.”')
w('Standard English Conventions','Modifiers','Built to withstand powerful winds, ___.\nWhich choice completes the text so that it conforms to Standard English?',['the tower has a reinforced core','engineers reinforced the tower’s core','a reinforced core was chosen by engineers','powerful winds required a reinforced core'],'The thing built to withstand winds is the tower, so “the tower” must immediately follow the opening modifier.')
w('Standard English Conventions','Verb tense','By the time the exhibition opened in 2022, the artist ___ on the series for six years.\nWhich choice completes the text so that it conforms to Standard English?',['had worked','will work','has worked','works'],'The work began before another past event. Past perfect “had worked” marks that earlier past interval.')
w('Standard English Conventions','Pronouns','Each of the two laboratories submitted ___ own results.\nWhich choice completes the text so that it conforms to Standard English?',['its','their','they’re','it’s'],'“Each” is singular, requiring “its.” “It’s” means “it is,” not possession.','easy')
w('Standard English Conventions','Boundaries','The expedition required three supplies ___ water, rope, and a compass.\nWhich choice completes the text so that it conforms to Standard English?',[':',';',',',' and'],'A colon may introduce a list after a complete clause. The words before the blank form a complete clause.','easy')
w('Standard English Conventions','Punctuation','The team’s first prototype ___ a compact solar-powered boat ___ completed the crossing.\nWhich pair of marks best completes the text so that it conforms to Standard English?',['— / —','; / ;',': / ,',', / ;'],'The phrase renames the prototype and interrupts the main clause. A matching pair of dashes encloses it; the main sentence is “The team’s first prototype completed the crossing.”')
w('Expression of Ideas','Transitions','The first battery stored more energy than the second. The second, ___ lasted through more charging cycles.\nWhich choice completes the text with the most logical transition?',['however,','therefore,','for example,','similarly,'],'The second battery has a different advantage, contrasting with the first comparison. “However” signals that contrast.','easy')
w('Expression of Ideas','Transitions','The sample was too small to support a reliable conclusion. ___ the researchers recruited additional participants.\nWhich choice completes the text with the most logical transition?',['Accordingly,','Nevertheless,','In contrast,','For instance,'],'Recruiting more participants follows from the small sample, so the transition must indicate a result.')
w('Expression of Ideas','Transitions','Several instruments can measure air pressure. A barometer, ___ uses the height of a liquid column or changes in a sealed chamber.\nWhich choice completes the text with the most logical transition?',['for example,','instead,','nevertheless,','consequently,'],'The barometer is a specific example of the instruments introduced in the first sentence.','easy')
w('Expression of Ideas','Rhetorical Synthesis','A student’s notes:\n• Artist Mara Vale works with recycled glass.\n• Her installation Tides contains 600 glass pieces.\n• The pieces hang at different heights.\n• Moving light creates shifting shadows.\nThe student wants to explain how light affects the installation. Which choice best uses relevant information?',['Light passing through Vale’s hanging glass pieces creates changing shadows.','Vale uses 600 pieces of recycled glass in Tides.','Vale is an artist who works with recycled glass.','The pieces in Tides hang at different heights.'],'Only the first choice explains the effect of light. Other choices give true background facts but omit the stated goal.')
w('Expression of Ideas','Rhetorical Synthesis','A student’s notes:\n• Two researchers measured the same shoreline.\n• One used 10-meter segments and reported 42 kilometers.\n• The other used 1-meter segments and reported 47 kilometers.\n• Smaller segments followed more small bends.\nThe student wants to explain the difference between the measurements. Which choice best uses the notes?',['The 1-meter segments captured more small bends, producing a longer measured shoreline.','Both researchers measured the same shoreline.','The reported lengths were 42 and 47 kilometers.','One researcher used 10-meter segments.'],'The goal asks why the lengths differ. The first answer connects finer segments to additional bends and greater measured length.','hard')
w('Standard English Conventions','Parallel structure','The workshop teaches participants to sketch a plan, to choose materials, and ___.\nWhich choice completes the text so that it conforms to Standard English?',['to assemble a model','assembling a model','a model is assembled','the assembly of a model'],'The list uses parallel infinitives: to sketch, to choose, and to assemble.','easy')
w('Standard English Conventions','Possessives','The two dancers rehearsed separately, but the ___ final performance was a duet.\nWhich choice completes the text so that it conforms to Standard English?',['dancers’','dancer’s','dancers','dancers’s'],'Two dancers possess the performance. Use plural dancers followed by an apostrophe.','easy')
w('Expression of Ideas','Rhetorical Synthesis','A student’s notes:\n• Cobalt blue is a pigment.\n• It was developed in the early nineteenth century.\n• It resists fading in sunlight.\n• Artists also used other blue pigments that faded more easily.\nThe student wants to emphasize an advantage of cobalt blue. Which choice best uses the notes?',['Unlike some other blue pigments, cobalt blue resists fading in sunlight.','Cobalt blue was developed in the early nineteenth century.','Artists used more than one blue pigment.','Cobalt blue is a pigment used by artists.'],'The contrast emphasizes fade resistance, the relevant advantage. Development date and general use do not explain that advantage.')
w('Standard English Conventions','Boundaries','Although the hike was long ___ the team reached camp before sunset.\nWhich choice completes the text so that it conforms to Standard English?',[',',';','.',':'],'The opening “although” clause is dependent. Separate it from the following independent clause with a comma, not a semicolon.','easy')
w('Standard English Conventions','Subject-Verb Agreement','The number of applications received this year ___ higher than expected.\nWhich choice completes the text so that it conforms to Standard English?',['is','are','have been','were'],'The subject is the singular “number,” not “applications.” Use the singular verb “is.”','easy')
w('Expression of Ideas','Transitions','The researcher repeated the measurement with a different instrument. ___ the second reading matched the first.\nWhich choice completes the text with the most logical transition?',['Notably,','Conversely,','Instead,','For instance,'],'“Notably” highlights the agreement as significant. There is no reversal, replacement, or example relationship here.')
# Science includes distinct data, controls, interpolation, and competing predictions.
add('science','Data Representation','Reading tables','A solution’s conductivity (units) was measured at 10°C: 4; 20°C: 7; 30°C: 10; 40°C: 13. Assuming the pattern continues linearly, what value is predicted at 50°C?',['16','14','15','20'],'Each 10°C increase adds 3 units. Add 3 to 13 to predict 16.','easy')
add('science','Research Summaries','Experimental controls','Researchers compare plant growth under red and blue lamps. Which condition should be held constant to isolate the effect of light color?',['The number of hours of light per day','The color of light','The measured growth after two weeks','The label assigned to each group'],'Daily exposure time should be the same. Color is the tested variable; growth is the measured outcome.')
add('science','Conflicting Viewpoints','Evaluating evidence','Scientist 1 predicts that a crater was formed by an impact. Scientist 2 predicts that it formed by collapse of an underground cavity. Which finding most directly supports Scientist 1?',['Rock fragments containing shock features produced by very high pressure','A circular depression visible at the surface','Loose soil around the depression','Rainwater collecting inside the depression'],'Shock features from very high pressure support an impact specifically; the other findings could occur in either type of crater.','hard')
add('science','Data Representation','Interpolation','A spring stretches 2 cm under a 100 g mass and 6 cm under a 300 g mass. In this range stretch is proportional to mass. What stretch is predicted for 250 g?',['5 cm','4 cm','8 cm','12 cm'],'The rate is 2 cm per 100 g. For 250 g, multiply 2 by 2.5 to obtain 5 cm.','easy')
add('science','Research Summaries','Interpreting experiments','A reaction finishes faster at 40°C than at 20°C when all other conditions are identical. What conclusion is supported by these trials?',['Higher temperature increased the reaction rate under the tested conditions.','Temperature has no effect on the reaction.','The reaction will be fastest at every temperature above 40°C.','The amount of reactant doubled at 40°C.'],'Completing the same reaction sooner means a higher rate. The trials establish this comparison, not behavior at untested temperatures.')
add('science','Conflicting Viewpoints','Comparing predictions','Student 1 predicts dissolved salt increases water’s boiling temperature. Student 2 predicts it decreases that temperature. Which measurement most directly distinguishes their predictions?',['Boiling temperatures of equal amounts of pure water and saltwater at the same pressure','The color of solid salt before dissolution','The mass of an empty beaker','The time needed to stir pure water'],'Both claims concern boiling temperature. Compare that outcome while keeping pressure and water amounts controlled.')
add('science','Data Representation','Rates of change','A sensor recorded distance at 0 s: 0 m; 2 s: 6 m; 4 s: 18 m; 6 s: 36 m. In which interval was average speed greatest?',['4–6 s','0–2 s','2–4 s','All intervals were equal.'],'The distances traveled in equal two-second intervals are 6, 12, and 18 m. The last interval has the greatest average speed.')
add('science','Research Summaries','Study design','A researcher tests a medicine using volunteers who are randomly assigned to receive the medicine or an identical-looking placebo. Why use random assignment?',['To reduce systematic differences between the treatment groups','To ensure the medicine works for every volunteer','To make every volunteer receive the medicine','To eliminate the need to measure outcomes'],'Random assignment helps balance other characteristics between groups, supporting comparison. It does not guarantee effectiveness or remove measurement needs.')
add('science','Conflicting Viewpoints','Evaluating evidence','One explanation for a lake’s reduced clarity is suspended mineral particles; another is increased algae. Which result would favor the algae explanation?',['Microscopy shows abundant algal cells in the cloudy water','The lake is less clear than last year','The water level changed slightly','The sampling bottles are transparent'],'Abundant algal cells identify a proposed source of cloudiness. The remaining observations do not distinguish algae from mineral particles.')
# Keep the text being edited within the Digital SAT's 25–150-word range.
contexts = {
19: 'Astronomers were monitoring an unusually quiet region of the sky during a routine overnight observation at the observatory.',
20: 'The museum had announced an exhibition of a painter’s early work, but several important pieces remained in storage during the renovation.',
21: 'The structure stands near a coastal research station, where storms frequently interrupt ordinary maintenance work and make long-term durability essential.',
22: 'The exhibition included paintings from several stages of the artist’s career and displayed the completed series together for the first time.',
23: 'The project compared two laboratories that followed the same procedure, with separate staff members recording observations before the results were combined.',
24: 'Before leaving camp, the group checked its equipment carefully because the planned route passed through unfamiliar terrain far from the nearest town.',
25: 'The project challenged students to design an efficient vessel using a limited set of materials and test it on a calm section of the river.',
26: 'An engineering team compared two battery designs intended for equipment that must operate reliably over many months of repeated use.',27: 'The study examined a possible link between sleep and memory, but the original participant group included only a few students.',28: 'Engineers use readings from different instruments to monitor changes in weather and to decide when outdoor testing conditions are suitable.',29: '', 30: '', 31: 'Participants build a small structure during the session, using a procedure that begins with planning and ends with a finished physical object.',
32: 'The theater’s new program featured a short piece created by two performers, who practiced their individual movements before bringing them together onstage.',
34: 'The group followed a winding trail through the valley, stopping briefly to record observations before continuing toward the campsite at the edge of the forest.',
35: 'Organizers expanded the program after receiving interest from students at several neighboring schools, and they are now deciding how many places to offer.',
36: 'The laboratory’s procedure called for checking an initial result with a separate device before using the measurement in a larger set of calculations.'
}
# Indexes are stable content IDs, not answer positions.
for item in banks['rw']:
    number=int(item['id'].rsplit('-',1)[1])
    if item.get('kind')=='reading' and len(item['passage'].split())<25:
        additions={1:'The critic described this deliberate approach as central to the pianist’s interpretation.',6:'The researcher plans to compare routes that differ in both speed and consistency to test this idea.',12:'The planner proposes studying access information before recommending costly changes inside the park.',2:'This revision broadens its scope while retaining a connection to earlier research.',3:'The argument depends on evidence that earlier summaries had not considered.',11:'The editor points to the funding requirement as an essential limit on the essay’s recommendation.',18:'She expects that future studies covering additional seasons may strengthen or change the explanation.'}
        item['passage']+=' '+additions[number]
    elif item.get('kind')=='writing':
        stem=item['q'].split('\nWhich')[0]
        if len(stem.split())<25:
            item['q']=contexts[number]+' '+item['q']
path=Path('SAT & ACT Practice.html');text=path.read_text();start='// ---- DISTINCT VARIETY EXPANSION ----';end='// ---- END DISTINCT VARIETY EXPANSION ----'
block=start+'\n'+''.join(('ACT_SCIENCE' if bank=='science' else 'BANK.'+bank)+'.push(\n'+',\n'.join(json.dumps(q,ensure_ascii=False) for q in items)+'\n);\n' for bank,items in banks.items())+end+'\n'
if start in text:
 a=text.index(start);b=text.index(end,a)+len(end)+1;text=text[:a]+block+text[b:]
else:text=text.replace('/*__DATA_END__*/',block+'/*__DATA_END__*/',1)
path.write_text(text);print({b:len(v) for b,v in banks.items()})
