"""Build original practice items aligned with the published SAT skill domains.
These are author-created models, not released College Board or ACT questions.
"""
import json
from pathlib import Path
from fractions import Fraction
banks = {'math': [], 'rw': [], 'science': []}

def add(bank, domain, skill, prompt, correct, wrong, explanation, diff='medium', **extra):
    prefix = {'math':'m','rw':'r' if extra.get('kind') == 'reading' else 'w','science':'s'}[bank]
    choices = list(map(str, [correct] + wrong))
    assert len(choices) == 4 and len(set(choices)) == 4, (prompt, choices)
    rotate = len(banks[bank]) % 4
    choices = choices[rotate:] + choices[:rotate]
    item = dict(id=f'{prefix}{1000+len(banks[bank])}', domain=domain, skill=skill, diff=diff,
                q=prompt, choices=choices, ans=choices.index(str(correct)), exp=explanation,
                source='Original practice modeled on published test skills', **extra)
    banks[bank].append(item)

def num(domain,skill,prompt,answer,exp,diff):
    add('math',domain,skill,prompt,answer,[answer+1,answer-1,answer+3],exp,diff)

for level,diff in enumerate(['easy','medium','hard']):
 for j in range(3):
    t=level*3+j+2; a=t+2; b=t+5; x=t+4
    num('Algebra','Linear equations in one variable',f'What value of x satisfies {a}x + {b} = {a*x+b}?',x,f'Subtract {b} from both sides to obtain {a}x = {a*x}. Divide by {a}: x = {x}.',diff)
    num('Algebra','Linear equations in two variables',f'A line is defined by y = {a}x − {b}. What is y when x = {x}?',a*x-b,f'Replace x with {x}: y = {a}({x}) − {b} = {a*x-b}. The question asks for y, not the slope.',diff)
    num('Algebra','Linear functions',f'A bicycle rental costs a fixed ${b} plus ${a} per hour. A customer pays ${b+a*x}. For how many hours did the customer rent the bicycle?',x,f'Remove the fixed fee: {b+a*x} − {b} = {a*x}. Divide by the hourly cost {a} to obtain {x} hours.',diff)
    num('Algebra','Systems of two linear equations',f'The equations x + y = {2*t+7} and x − y = 5 form a system. What is the value of x?',t+6,f'Add the equations so y cancels: 2x = {2*t+12}. Divide by 2 to get x = {t+6}. Then y = {t+1}, which satisfies both equations.',diff)
    num('Algebra','Linear inequalities',f'What is the least integer x for which {a}x − {b} > {a*t-b}?',t+1,f'Add {b}, then divide by positive {a}: x > {t}. Since the inequality is strict, the smallest integer is {t+1}.',diff)
    num('Advanced Math','Equivalent expressions',f'The expression {a}(x + {t}) − {t}x is equivalent to 2x + c. What is the value of c?',a*t,f'Distribute: {a}x + {a*t} − {t}x = 2x + {a*t}. Therefore c = {a*t}.',diff)
    num('Advanced Math','Quadratic equations',f'The equation (x − {t})(x − {t+7}) = 0 has two solutions. What is the larger solution?',t+7,f'A product is zero when at least one factor is zero. The solutions are {t} and {t+7}; the larger is {t+7}.',diff)
    num('Advanced Math','Nonlinear functions',f'The function f is defined by f(x) = (x − {t})² + {b}. What is the minimum value of f(x)?',b,f'The square cannot be negative and is zero at x = {t}. Thus the smallest output is {b}; {t} is where the minimum occurs, not the minimum value.',diff)
    num('Advanced Math','Radical equations',f'What value of x satisfies √(x + {b}) = {a}?',a*a-b,f'Square both sides: x + {b} = {a*a}. Subtract {b}: x = {a*a-b}. Substitution gives √{a*a} = {a}, so the result is valid.',diff)
    num('Advanced Math','Exponential functions',f'A culture begins with {t*10} cells and doubles every hour. How many cells does the model predict after 3 hours?',t*80,f'Three doublings multiply the starting amount by 2³ = 8. Thus {t*10} × 8 = {t*80} cells.',diff)
    num('Problem-Solving & Data Analysis','Percentages',f'A jacket originally costs ${t*20}. Its price increases by 25%. What is the new price, in dollars?',t*25,f'An increase of 25% multiplies the original price by 1.25: {t*20} × 1.25 = {t*25}.',diff)
    num('Problem-Solving & Data Analysis','Ratios and proportional relationships',f'A paint mixture uses blue and white paint in a ratio of 3 to 5. If it contains {t*3} liters of blue paint, how many liters of white paint does it contain?',t*5,f'The scale factor is {t*3} ÷ 3 = {t}. Multiply the white part 5 by {t} to get {t*5} liters.',diff)
    num('Problem-Solving & Data Analysis','Measures of center',f'Four numbers are {t}, {t+2}, {t+4}, and {t+6}. What is their mean?',t+3,f'The sum is {4*t+12}. Divide by the count, 4, to obtain {t+3}.',diff)
    num('Problem-Solving & Data Analysis','Probability',f'A bag contains {t} red beads and {t+3} blue beads. One bead is chosen at random. If the probability of choosing red is written as {t}/n, what is n?',2*t+3,f'The denominator counts all beads: {t} + {t+3} = {2*t+3}. Favorable outcomes are the {t} red beads.',diff)
    num('Problem-Solving & Data Analysis','Unit rates',f'A printer produces {t*24} pages in 6 minutes at a constant rate. How many pages does it produce in 10 minutes?',t*40,f'The rate is {t*24} ÷ 6 = {t*4} pages per minute. Multiply by 10 minutes to get {t*40} pages.',diff)
    num('Geometry & Trigonometry','Area and volume',f'A right triangle has perpendicular sides of lengths {t*2} cm and {t+3} cm. What is its area, in square centimeters?',t*(t+3),f'Triangle area is ½ × base × perpendicular height: ½ × {t*2} × {t+3} = {t*(t+3)}.',diff)
    num('Geometry & Trigonometry','Circles',f'A circle has radius {t} centimeters. Its circumference is cπ centimeters. What is c?',2*t,f'Circumference is 2πr. Substitute r = {t} to get {2*t}π, so c = {2*t}.',diff)
    num('Geometry & Trigonometry','Right triangles',f'A right triangle has legs of lengths {3*t} and {4*t}. What is the length of its hypotenuse?',5*t,f'Use a² + b² = c²: ({3*t})² + ({4*t})² = {25*t*t}. The positive square root is {5*t}.',diff)

# Each scenario is fictional and self-contained, so all conclusions are grounded in its text.
scenarios = [
('library','A neighborhood library replaced its rigid checkout periods with flexible return dates. Late returns decreased, while the number of borrowed books increased. Staff concluded that the change made borrowing easier without worsening the return problem.', 'Flexible return dates can improve borrowing and reduce late returns.', 'Late returns decreased while borrowing increased.', 'show how a policy change produced useful results', 'Flexible return dates need not cause more late returns.'),
('wetland','A field team planted reeds along one section of a drainage channel and left a similar section bare. After rainstorms, water leaving the planted section contained less sediment. The team cautioned that its findings applied only to the conditions it measured.', 'Planted reeds reduced sediment under the tested conditions.', 'Water from the planted section contained less sediment.', 'report a result while limiting the scope of the conclusion', 'The findings do not establish what would happen under all possible conditions.'),
('museum','A museum displayed replicas beside fragile original objects. Visitors could handle the replicas but viewed the originals behind glass. Guides reported that visitors asked more questions about how the objects had been made after touching the replicas.', 'Replicas allowed hands-on learning while protecting originals.', 'Visitors asked more questions after touching replicas.', 'explain how an exhibit design served two goals', 'Hands-on replicas may encourage visitors to think about how objects were made.'),
('translation','Two translators rendered the same poem differently. One preserved the rhyme at the cost of changing several images. The other retained the images but used unrhymed lines. A critic argued that each version preserved one feature by sacrificing another.', 'Translating the poem involved tradeoffs between rhyme and imagery.', 'One version kept rhyme and the other kept images.', 'compare approaches to a difficult task', 'Neither translation preserved both features completely.'),
('archive','An archivist found receipts mixed with letters in a box labeled “personal correspondence.” The letters described friendships, while the receipts documented household purchases. Keeping both types of record revealed a fuller picture of daily life than the letters alone.', 'Different kinds of records together can reveal daily life more fully.', 'The receipts documented household purchases missing from the letters.', 'illustrate the value of combining types of evidence', 'The label on the box did not fully describe its contents.'),
('robot','A student built a robot that completed a maze quickly on a smooth floor. On a rough floor, its wheels slipped and it took longer. Rather than changing the route-finding code, the student first redesigned the tires.', 'A robot’s performance can depend on its physical design as well as its code.', 'The wheels slipped on the rough floor.', 'explain the reasoning behind a design revision', 'The student suspected that tire grip contributed to the slower performance.'),
('garden','A school garden used to grow only one variety of bean. After students added two other varieties, one survived a dry week better than the others. The teacher used the outcome to discuss why relying on a single variety could be risky.', 'Growing several varieties may help a garden withstand changing conditions.', 'One variety survived the dry week better than the others.', 'connect an observation to a broader lesson', 'The varieties responded differently to the same dry conditions.'),
('music','A composer recorded a melody on a piano and then on a flute. Listeners identified the same tune in both recordings but described the mood differently. The composer noted that instrument choice changed the experience without changing the sequence of notes.', 'The same melody can create different impressions on different instruments.', 'Listeners recognized the tune but described different moods.', 'distinguish a stable feature from a changing one', 'Recognizing a melody does not require listeners to experience it in the same way.'),
('transport','A town added an evening bus route. Surveys showed that some workers who had previously driven began using the bus. Weekend travelers, however, reported little change because the new route did not operate on weekends.', 'A transport change helped one group more than another.', 'Workers changed travel habits but weekend travelers did not.', 'describe the uneven effects of a service change', 'The schedule affected who could benefit from the route.'),
('restoration','A conservator removed a dark coating from a painted panel. Beneath it, several colors appeared brighter, but a damaged corner remained faded. She explained that removing a surface coating could reveal surviving color but could not replace pigment that was gone.', 'Cleaning can reveal preserved color but cannot restore missing pigment.', 'The damaged corner remained faded after cleaning.', 'clarify the limits of a restoration technique', 'The faded corner may have lost pigment rather than merely acquired a coating.'),
('mapping','An old map showed a stream where a modern map showed a road. Field measurements confirmed that the stream had been redirected into an underground pipe. The difference between the maps therefore recorded a change in the landscape rather than necessarily an error.', 'Differences between maps can reflect changes in a landscape.', 'Measurements confirmed that the stream had been redirected.', 'resolve an apparent contradiction with additional evidence', 'Both maps could accurately describe the landscape at different times.'),
('theater','An actor spoke the same line first in a cheerful tone and then in a weary tone. The words did not change, but the audience interpreted the character’s intention differently. The director used the exercise to show how delivery contributes to meaning.', 'Delivery can change how an audience interprets unchanged words.', 'The audience interpreted the same line differently after the tone changed.', 'illustrate how performance affects interpretation', 'The written words alone did not determine the audience’s interpretation.')
]
for i,(topic,passage,main,evidence,purpose,inference) in enumerate(scenarios):
    common={'kind':'reading','passage':passage}
    add('rw','Information & Ideas','Central Ideas and Details','Which choice best states the main idea of the text?',main,['Every approach described in the text failed completely.','The text argues that evidence is unnecessary.','The text shows that all circumstances produce identical results.'],f'The text’s observations support this central idea: {main} The other choices either contradict the observations or make unsupported absolute claims.','easy',**common)
    add('rw','Information & Ideas','Command of Evidence','Which detail from the text best supports its main conclusion?',evidence,['The observations were identical in every circumstance.','No change or comparison was described.','The text reports that all questions have already been resolved.'],f'The key supporting observation is that {evidence[0].lower()+evidence[1:]} It directly connects the described action or comparison to the conclusion.','medium',**common)
    add('rw','Craft & Structure','Text Structure and Purpose','Which choice best describes the overall purpose of the text?',purpose,['to argue that measurements should be ignored','to list unrelated events without explaining their connection','to establish that one example proves a universal rule'],f'The text is organized to {purpose}. It explains a connection rather than merely listing events or claiming certainty in all cases.','medium',**common)
    add('rw','Information & Ideas','Inferences','Which inference is most strongly supported by the text?',inference,['The result must apply unchanged in every setting.','The people described had no reason for their decisions.','The stated observations never took place.'],f'The observations support this limited inference: {inference} The text does not justify extending the conclusion to every setting.','hard',**common)
    add('rw','Craft & Structure','Cross-Text Connections',f'Text 1: {passage}\n\nText 2: A commentator argues that this example proves the same outcome must occur in every possible setting.\n\nHow would the author of Text 1 most likely respond to the commentator in Text 2?', 'The commentator draws a broader conclusion than the specific evidence establishes.', ['The commentator provides measurements that contradict every observation.','The commentator accurately quotes a universal rule explicitly stated in Text 1.','The commentator shows that the events in Text 1 never happened.'], 'Text 1 describes a specific situation. Text 2 extends it to every possible setting without additional evidence. The cautious response is to reject that unsupported generalization.','hard',kind='reading')

# Sentence boundaries, agreement, modifiers, tense, pronouns, and rhetorical goals.
subjects=[('botanist','seed collection'),('curator','exhibit catalog'),('engineer','bridge design'),('historian','archive index'),('astronomer','star chart'),('librarian','reading list'),('composer','concert program'),('archaeologist','site report'),('editor','manuscript review'),('ecologist','habitat survey'),('geologist','rock inventory'),('designer','fabric sample')]
for i,(person,project) in enumerate(subjects):
    add('rw','Standard English Conventions','Subject-Verb Agreement',f'The {person}’s collection of notes ___ useful for the {project}.\nWhich choice completes the text so that it conforms to Standard English?', 'is',['are','were','have been'], 'The singular subject is “collection,” not the plural word “notes.” A singular present-tense verb is needed, so “is” is correct.','easy',kind='writing')
    add('rw','Standard English Conventions','Boundaries',f'The {person} completed the {project} ___ the team then reviewed it.\nWhich choice completes the text so that it conforms to Standard English?', ';',[',','',': and'], 'Both sides are complete sentences. A semicolon joins two independent clauses. A comma alone makes a comma splice; no punctuation makes a run-on. “: and” does not correctly join these clauses.','medium',kind='writing')
    add('rw','Standard English Conventions','Modifiers',f'After reviewing the {project}, ___\nWhich choice completes the text so that it conforms to Standard English?', f'the {person} revised the notes.', ['the notes required revisions.','a revision was necessary.','several errors were discovered.'], f'The person who reviewed the {project} must immediately follow the opening phrase. Only “the {person}” can logically do the reviewing. The other choices create dangling modifiers.','hard',kind='writing')
    add('rw','Standard English Conventions','Possessives',f'Two {person}s each wrote a report. Both reports were displayed. The label read “The ___ reports.”\nWhich choice completes the text so that it conforms to Standard English?', f'{person}s’',[f'{person}’s',f'{person}s',f'{person}s’s'], f'Two people own the reports, so the owner is plural: {person}s. Put the apostrophe after the plural s to show shared possession.','medium',kind='writing')
    old=40+i*5;new=old+20
    notes=f'While researching a topic, a student took these notes:\n• A team counted visits to a fictional {project} display.\n• Before a new sign was added, the display received {old} visits per day.\n• After the sign was added, it received {new} visits per day.\n• Both counts covered the same number of days.'
    add('rw','Expression of Ideas','Rhetorical Synthesis',f'{notes}\n\nThe student wants to emphasize the change in daily visits. Which choice most effectively uses relevant information from the notes?',f'Daily visits rose from {old} before the sign to {new} after it.', ['The team studied a display and used notes.','Both counts covered the same number of days.',f'The display had {new} visits before the sign and {old} after it.'], f'The goal is to emphasize change, so the answer must include both the before value ({old}) and the after value ({new}) in the correct order. The other choices omit the change or reverse it.','easy',kind='writing')
    add('rw','Expression of Ideas','Transitions',f'The {person} expected the {project} to take a month. ___ it was completed in only a week.\nWhich choice completes the text with the most logical transition?', 'However,',['Therefore,','For example,','Similarly,'], 'The second sentence contrasts the actual result with the expectation. “However” signals contrast. The other transitions signal result, example, or similarity.','easy',kind='writing')
    add('rw','Expression of Ideas','Transitions',f'The team discovered an error in the {project}. ___ the {person} delayed its release to make a correction.\nWhich choice completes the text with the most logical transition?', 'Consequently,',['Nevertheless,','Likewise,','For instance,'], 'Delaying release is a result of discovering the error. “Consequently” shows cause and effect. The other choices imply contrast, similarity, or an example.','medium',kind='writing')
    add('rw','Expression of Ideas','Rhetorical Synthesis',f'{notes}\n\nThe student wants to describe a limitation of using these counts to claim the sign alone caused the change. Which choice best accomplishes this goal?', 'The notes do not establish whether other conditions changed when the sign was added.', [f'The count increased by {new-old} visits per day.','The team counted visits before and after adding the sign.','The two counting periods lasted the same number of days.'], 'A before-and-after comparison shows a change but does not isolate its cause. Other conditions might have changed too. Equal observation lengths help comparison but do not eliminate possible confounding factors.','hard',kind='writing')

for i in range(12):
    v=i+2
    table=f'A fictional trial measured how far a cart traveled in equal time intervals on three surfaces.\nSurface A: {v*3} m; Surface B: {v*5} m; Surface C: {v*4} m.'
    add('science','Data Representation','Reading tables',table+'\nOn which surface did the cart travel farthest?', 'Surface B',['Surface A','Surface C','The distances were equal.'],f'Surface B’s value ({v*5} m) is larger than {v*3} m and {v*4} m. Compare the recorded distances directly.','easy')
    add('science','Research Summaries','Experimental controls',f'In Trial {i+1}, a team tests whether the mass of a cart affects its travel distance. They use the same ramp height and surface for every run. Which procedure best tests their question?', 'Change only the cart’s mass and measure its travel distance.', ['Change the ramp height and surface together.','Keep the cart mass fixed and change the surface.','Measure the cart color without running it.'], 'The independent variable is mass and the dependent variable is travel distance. Holding ramp height and surface constant helps isolate the effect of mass.','medium')
    add('science','Conflicting Viewpoints','Evaluating evidence',f'In a fictional investigation of Sample {i+1}, Student 1 claims its dark color comes from a surface coating. Student 2 claims the color is part of the material itself. Which observation would most directly support Student 1?', 'Removing a thin outer layer reveals lighter material underneath.', ['The sample is dark before any test.','The sample has measurable mass.','Both students examine the same sample.'], 'A lighter interior after the outer layer is removed supports the idea of a dark surface coating. The other observations do not distinguish the two explanations.','hard')

for bank,items in banks.items():
    assert len({q['q'] + q.get('passage','') for q in items})==len(items), bank
p=Path('SAT & ACT Practice.html')
s=p.read_text();start='// ---- ORIGINAL MODELED PRACTICE EXPANSION ----';end='// ---- END MODELED PRACTICE EXPANSION ----'
block=start+'\n'
for bank,items in banks.items():
    target='ACT_SCIENCE' if bank=='science' else 'BANK.'+bank
    block+=target+'.push(\n'+',\n'.join(json.dumps(q,ensure_ascii=False) for q in items)+'\n);\n'
block+=end+'\n'
if start in s:
    a=s.index(start);b=s.index(end,a)+len(end)+1;s=s[:a]+block+s[b:]
else:s=s.replace('/*__DATA_END__*/',block+'/*__DATA_END__*/',1)
p.write_text(s)
print({bank:len(items) for bank,items in banks.items()})
