#!/usr/bin/env python3
"""Drop and re-file the college photos the current filters reject, offline.

scripts/build-college-data.py is the real fix: it re-crawls Commons, re-derives
each photo's category from the file title *and* its Commons description, and
refills every gallery to six. This script is the half of that job that needs no
network, for when Commons is unreachable -- it takes the photos already in
college-data.js and removes the ones today's filters reject, so the site stops
showing a mis-filed photo while it waits for a crawl.

It only acts on positive evidence from the Commons file name, which is all the
bundle carries:

  drop     game action (ACTION_MARKERS) -- a road game is shot at the
           opponent's stadium, which is how a Jim Harbaugh photo taken at
           Michigan Stadium came to sit under University of San Diego
  drop     Internet Archive book-page scans (SCANNED_PAGE)
  re-file  a photo stored as athletics that names no venue but that photo_kind
           now places in another category -- the photo is fine, the label was
           stale
  drop     a photo stored as athletics that names no venue and that photo_kind
           places nowhere at all -- nothing in the file name supports any
           gallery category, so the stored category cannot be trusted

Everything else is left exactly as it was. Dropping is not destructive to the
pipeline: a gallery that falls under six photos is re-crawled on the next run.

  python3 scripts/prune-college-photos.py [--dry-run]
"""
import argparse
import importlib.util
import json
import os
import re
import sys
import urllib.parse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUNDLE = os.path.join(ROOT, "college-data.js")
HEADER = "/* Generated by scripts/build-college-data.py. Do not edit by hand. */\n"


def load_pipeline():
    """Reuse the pipeline's own predicates so this cannot drift from the crawl."""
    path = os.path.join(ROOT, "scripts", "build-college-data.py")
    spec = importlib.util.spec_from_file_location("build_college_data", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def file_name(photo):
    """The Commons file name, decoded and readable: "Kyle Field aerial.jpg"."""
    raw = str(photo.get("l") or photo.get("u") or "")
    tail = raw.split("/wiki/")[-1] if "/wiki/" in raw else raw.rsplit("/", 1)[-1]
    try:
        tail = urllib.parse.unquote(tail)
    except Exception:
        pass
    return re.sub(r"^File:?", "", tail, flags=re.I).replace("_", " ")


def read_bundle():
    raw = open(BUNDLE, encoding="utf-8").read()
    match = re.search(r"window\.COLLEGE_DATA\s*=\s*(\{[\s\S]*\})\s*;?\s*$", raw)
    if not match:
        sys.exit("college-data.js does not match the expected shape")
    return json.loads(match.group(1))


def write_bundle(payload):
    with open(BUNDLE, "w", encoding="utf-8") as handle:
        handle.write(HEADER)
        handle.write("window.COLLEGE_DATA = ")
        json.dump(payload, handle, ensure_ascii=False, separators=(",", ":"))
        handle.write(";\n")


def verdict(bcd, photo):
    """(action, detail) where action is "keep", "drop" or a new category kind."""
    name = file_name(photo)
    low = name.lower()

    hits = [m for m in bcd.ACTION_MARKERS if m in low]
    if hits:
        return "drop", "game action (%s)" % ", ".join(h.strip() for h in hits[:3])
    if bcd.scanned_page(name):
        return "drop", "scanned book page"
    rejected = [b for b in bcd.LEGACY_REJECT if b in low]
    if rejected:
        return "drop", "rejected subject (%s)" % ", ".join(rejected[:3])

    if photo.get("kind") == "athletics" and not any(w in low for w in bcd.VENUE_WORDS):
        derived = bcd.photo_kind(low)
        if derived and derived != "athletics":
            return derived, "stale label: athletics -> %s" % derived
        return "drop", "athletics but the file name names no venue"

    return "keep", ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="report what would change without rewriting the bundle")
    args = ap.parse_args()

    bcd = load_pipeline()
    payload = read_bundle()
    colleges = payload.get("colleges") or []

    dropped, refiled = [], []
    before = after = 0

    for college in colleges:
        photos = college.get("imgs") or []
        if not photos:
            continue
        before += len(photos)
        kept = []
        for photo in photos:
            action, detail = verdict(bcd, photo)
            name = file_name(photo)
            if action == "drop":
                dropped.append((college["n"], name, detail))
                continue
            if action != "keep":
                photo = dict(photo, kind=action,
                             label=bcd.PHOTO_LABELS.get(action, bcd.PHOTO_LABELS["campus"]))
                refiled.append((college["n"], name, detail))
            kept.append(photo)
        after += len(kept)
        if kept:
            college["imgs"] = kept
        else:
            college.pop("imgs", None)

    for label, rows in (("DROPPED", dropped), ("RE-FILED", refiled)):
        print("--- %s (%d) ---" % (label, len(rows)))
        for who, name, detail in rows:
            print("  %-38s %-70s %s" % (who[:38], name[:70], detail))
        print()

    galleries = sum(1 for c in colleges if c.get("imgs"))
    print("photos %d -> %d (%d dropped, %d re-filed)"
          % (before, after, len(dropped), len(refiled)))
    print("colleges with a gallery: %d" % galleries)
    print("galleries now under six photos (a crawl will refill): %d"
          % sum(1 for c in colleges if 0 < len(c.get("imgs") or []) < 6))

    if args.dry_run:
        print("\ndry run: college-data.js untouched")
        return
    if dropped or refiled:
        payload.setdefault("meta", {})["count"] = len(colleges)
        write_bundle(payload)
        print("\nrewrote %s" % os.path.relpath(BUNDLE, ROOT))
    else:
        print("\nnothing to change")


if __name__ == "__main__":
    main()
